news_theme.settings:
  type: theme_settings
  label: 'News Theme settings'
  mapping:
    footer_site_name:
      type: text
      label: 'Footer site name'
    footer_description:
      type: text
      label: 'Footer description'
      translatable: true
    footer_email:
      type: text
      label: 'Footer email address'
    footer_facebook:
      type: text
      label: 'Facebook URL'
    footer_twitter:
      type: text
      label: 'Twitter URL'
    footer_instagram:
      type: text
      label: 'Instagram URL'
    footer_youtube:
      type: text
      label: 'YouTube URL'
    footer_github:
      type: text
      label: 'GitHub URL'
    footer_medium:
      type: text
      label: 'Medium URL'
    newsletter_header:
      type: text
      label: 'Newsletter header'
      translatable: true
    language_switcher_domains:
      type: sequence
      label: 'Language switcher domains'
      sequence:
        type: text
    language_switcher_hide_anonymous:
      type: boolean
      label: 'Hide language switcher for anonymous users'
